languages = {
    "af": {"name": "Afrikaans", "size": "305M"},
    "am": {"name": "Amharic", "size": "133M"},
    "ar": {"name": "Arabic", "size": "5.4G"},
    "as": {"name": "Assamese", "size": "7.6M"},
    "az": {"name": "Azerbaijani", "size": "1.3G"},
    "be": {"name": "Belarusian", "size": "692M"},
    "bg": {"name": "Bulgarian", "size": "9.3G"},
    "bn": {"name": "Bengali", "size": "860M"},
    "bn_rom": {"name": "Bengali Romanized", "size": "164M"},
    "br": {"name": "Breton", "size": "21M"},
    "bs": {"name": "Bosnian", "size": "18M"},
    "ca": {"name": "Catalan", "size": "2.4G"},
    "cs": {"name": "Czech", "size": "4.4G"},
    "cy": {"name": "Welsh", "size": "179M"},
    "da": {"name": "Danish", "size": "12G"},
    "de": {"name": "German", "size": "18G"},
    "el": {"name": "Greek", "size": "7.4G"},
    "en": {"name": "English", "size": "82G"},
    "eo": {"name": "Esperanto", "size": "250M"},
    "es": {"name": "Spanish", "size": "14G"},
    "et": {"name": "Estonian", "size": "1.7G"},
    "eu": {"name": "Basque", "size": "488M"},
    "fa": {"name": "Persian", "size": "20G"},
    "ff": {"name": "Fulah", "size": "3.1M"},
    "fi": {"name": "Finnish", "size": "15G"},
    "fr": {"name": "French", "size": "14G"},
    "fy": {"name": "Frisian", "size": "38M"},
    "ga": {"name": "Irish", "size": "108M"},
    "gd": {"name": "Scottish Gaelic", "size": "22M"},
    "gl": {"name": "Galician", "size": "708M"},
    "gn": {"name": "Guarani", "size": "1.5M"},
    "gu": {"name": "Gujarati", "size": "242M"},
    "ha": {"name": "Hausa", "size": "61M"},
    "he": {"name": "Hebrew", "size": "6.1G"},
    "hi": {"name": "Hindi", "size": "2.5G"},
    "hi_rom": {"name": "Hindi Romanized", "size": "129M"},
    "hr": {"name": "Croatian", "size": "5.7G"},
    "ht": {"name": "Haitian", "size": "9.1M"},
    "hu": {"name": "Hungarian", "size": "15G"},
    "hy": {"name": "Armenian", "size": "776M"},
    "id": {"name": "Indonesian", "size": "36G"},
    "ig": {"name": "Igbo", "size": "6.6M"},
    "is": {"name": "Icelandic", "size": "779M"},
    "it": {"name": "Italian", "size": "7.8G"},
    "ja": {"name": "Japanese", "size": "15G"},
    "jv": {"name": "Javanese", "size": "37M"},
    "ka": {"name": "Georgian", "size": "1.1G"},
    "kk": {"name": "Kazakh", "size": "889M"},
    "km": {"name": "Khmer", "size": "153M"},
    "kn": {"name": "Kannada", "size": "360M"},
    "ko": {"name": "Korean", "size": "14G"},
    "ku": {"name": "Kurdish", "size": "90M"},
    "ky": {"name": "Kyrgyz", "size": "173M"},
    "la": {"name": "Latin", "size": "609M"},
    "lg": {"name": "Ganda", "size": "7.3M"},
    "li": {"name": "Limburgish", "size": "2.2M"},
    "ln": {"name": "Lingala", "size": "2.3M"},
    "lo": {"name": "Lao", "size": "63M"},
    "lt": {"name": "Lithuanian", "size": "3.4G"},
    "lv": {"name": "Latvian", "size": "2.1G"},
    "mg": {"name": "Malagasy", "size": "29M"},
    "mk": {"name": "Macedonian", "size": "706M"},
    "ml": {"name": "Malayalam", "size": "831M"},
    "mn": {"name": "Mongolian", "size": "397M"},
    "mr": {"name": "Marathi", "size": "334M"},
    "ms": {"name": "Malay", "size": "2.1G"},
    "my": {"name": "Burmese", "size": "46M"},
    "my_zaw": {"name": "Burmese (Zawgyi)", "size": "178M"},
    "ne": {"name": "Nepali", "size": "393M"},
    "nl": {"name": "Dutch", "size": "7.9G"},
    "no": {"name": "Norwegian", "size": "13G"},
    "ns": {"name": "Northern Sotho", "size": "1.8M"},
    "om": {"name": "Oromo", "size": "11M"},
    "or": {"name": "Oriya", "size": "56M"},
    "pa": {"name": "Punjabi", "size": "90M"},
    "pl": {"name": "Polish", "size": "12G"},
    "ps": {"name": "Pashto", "size": "107M"},
    "pt": {"name": "Portuguese", "size": "13G"},
    "qu": {"name": "Quechua", "size": "1.5M"},
    "rm": {"name": "Romansh", "size": "4.8M"},
    "ro": {"name": "Romanian", "size": "16G"},
    "ru": {"name": "Russian", "size": "46G"},
    "sa": {"name": "Sanskrit", "size": "44M"},
    "si": {"name": "Sinhala", "size": "452M"},
    "sc": {"name": "Sardinian", "size": "143K"},
    "sd": {"name": "Sindhi", "size": "67M"},
    "sk": {"name": "Slovak", "size": "6.1G"},
    "sl": {"name": "Slovenian", "size": "2.8G"},
    "so": {"name": "Somali", "size": "78M"},
    "sq": {"name": "Albanian", "size": "1.3G"},
    "sr": {"name": "Serbian", "size": "1.5G"},
    "ss": {"name": "Swati", "size": "86K"},
    "su": {"name": "Sundanese", "size": "15M"},
    "sv": {"name": "Swedish", "size": "21G"},
    "sw": {"name": "Swahili", "size": "332M"},
    "ta": {"name": "Tamil", "size": "1.3G"},
    "ta_rom": {"name": "Tamil Romanized", "size": "68M"},
    "te": {"name": "Telugu", "size": "536M"},
    "te_rom": {"name": "Telugu Romanized", "size": "79M"},
    "th": {"name": "Thai", "size": "8.7G"},
    "tl": {"name": "Tagalog", "size": "701M"},
    "tn": {"name": "Tswana", "size": "8.0M"},
    "tr": {"name": "Turkish", "size": "5.4G"},
    "ug": {"name": "Uyghur", "size": "46M"},
    "uk": {"name": "Ukrainian", "size": "14G"},
    "ur": {"name": "Urdu", "size": "884M"},
    "ur_rom": {"name": "Urdu Romanized", "size": "141M"},
    "uz": {"name": "Uzbek", "size": "155M"},
    "vi": {"name": "Vietnamese", "size": "28G"},
    "wo": {"name": "Wolof", "size": "3.6M"},
    "xh": {"name": "Xhosa", "size": "25M"},
    "yi": {"name": "Yiddish", "size": "51M"},
    "yo": {"name": "Yoruba", "size": "1.1M"},
    "zh-Hans": {"name": "Chinese (Simplified)", "size": "14G"},
    "zh-Hant": {"name": "Chinese (Traditional)", "size": "5.3G"},
    "zu": {"name": "Zulu", "size": "4.3M"},
}


def convert_size(size_str):
    size_dict = {"K": 1, "M": 1_000, "G": 1_000_000}
    return float(size_str[:-1]) * size_dict[size_str[-1]]


sorted_languages = sorted(
    languages.items(), key=lambda item: convert_size(item[1]["size"])
)

for code, info in sorted_languages:
    print(f"{code}: {info['name']} - {info['size']}")
